export { default as Bookings } from './Bookings'
export { default as Home } from './Home'
export { default as Location } from './Location'
export { default as Notfound } from './Notfound'
export { default as Product } from './Product'
export { default as Search } from './Search'